apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bauhaus-front
  labels:
    name: bauhaus-front
spec:
  rules:
  - host: gestion-metadonnees.demo.insee.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: bauhaus-front
            port: 
              number: 3000
