{{- if and .Values.api.enabled .Values.api.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-metrics" (include "queen.api.name" .) }}
  namespace: {{ include "queen.namespace" . | quote }}
  labels: {{- include "queen.api.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  {{- with .Values.api.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.metrics.service.type }}
  ports:
    - port: {{ .Values.api.metrics.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: http-metrics
  selector: 
    {{- include "queen.api.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: queen.api
{{- end -}}      