apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graphdb
  labels:
    name: graphdb
spec:
  rules:
  - host: gestion-metadonnees-bdb.demo.insee.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: graphdb
            port: 
              number: 7200
