apiVersion: v2
name: queen
description: A Helm chart for Queen API, UI and DB

dependencies:
  - name: postgresql
    condition: postgresql.enabled
    version: 11.6.15
    repository: https://charts.bitnami.com/bitnami

type: application
version: 0.2.3
appVersion: "1.16.0"
