{{- if .Values.postgresql.enabled }}
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{ include "app.ui.fullname" . }}
  labels:
    {{- include "app.postgresql.labels" . | nindent 4 }}
spec:
  postgresVersion: {{ .Values.postgresql.version }}
  instances:
    - name: instance1
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      repoHost:
        dedicated: {}
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
  monitoring:
    pgmonitor:
      exporter: {}
{{- end }}
